name: backend CI

on:
  push:
    branches:
      - develop
      - main
    paths:
      - "backend/**"
  workflow_dispatch:
defaults:
  run:
    working-directory: ./backend
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Test with Gradle
      run: ./gradlew test
      
    - name: Build with Gradle
      run: ./gradlew build

    - name: Make Directory
      run: mkdir -p deploy

    - name: Copy deployment pakage files
      run: |
        cp scripts/*.sh deploy/
        cp appspec.yml deploy/
        cp ./build/libs/*.jar deploy/

    - name: Make deployment zip file
      run: zip -r mwomeokji.zip ./deploy

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp mwomeokji.zip s3://mwomeokji/backend_build_files/ --acl private

    - name: Code Deploy
      run: aws deploy create-deployment
        --application-name mwomeokji
        --deployment-group-name mwomeokji
        --deployment-config-name CodeDeployDefault.AllAtOnce
        --s3-location bucket=mwomeokji,key=backend_build_files/mwomeokji.zip,bundleType=zip